### ISSUE TITLE
Suggestion CPL.4: Do note name member functions 'init' and 'free', use constructor and destructor instead

### ISSUE THREAD

**Issue by richelbilderbeek** [isocpp/CppCoreGuidelines#284] opened 2015-10-04 17:56 UTC
# CPL.4: Do note name member functions 'init' and 'free', use constructor and destructor instead

## Reason

In C it is a common idiom to initialize a struct with `init`, and destroy it using `free`.
In C++ a constructor and destructor are used for exactly this.

Additionally, an `init` member function has different behavior than the initializer list
in a contructor: `init` cannot initialize a const member variable without a `const_cast`

## Example

```
class MyClass {
  public:
  MyClass() { init(); } //No, just do init in constructor
  ~MyClass() { free(); } //No, just do free in destructor

  private:
  void init() { /* initialization */ }
  void free() { /* destroy */ }
};

```

```
class Person {
  public:
  Person(const int pin) { init(pin); } //No, just do initialization in constructor

  private:
  const int m_pin; //Every Person has a constant Personal Identification Number
  void init(const int pin) { 
    const_cast<Person&>(*this).m_pin = pin; //Could have prevented this const_cast
  } 
};

```

```
class Person {
  public:
  Person(const int pin) : m_pin{pin} {} //OK: use constructor its initializer list

  private:
  const int m_pin; //Every Person has a constant Personal Identification Number
};

```

## Exceptions

None

## Enforcement

None

## See alsos

None

## Notes

Yes, I really saw this in code.

## Discussion

None

**Comment by grahamreeds** [comment] 2015-10-04 21:47
The example, in my opinion, is poor.

The code base I work on has init (or in our parlance common() ) all over
the place. Not because we are all really poor coders but because pre 11 you
couldn't chain constructors which is why this occurred.

This also happened to lesser or greater extent at all the previous places I
worked.

So the example should be about chaining constructors now and not a guide
for C programmers moving to C++.

The title is correct but the reasoning is wrong(ish).

GR

**Comment by cubbimew** [comment] 2015-10-04 22:00
This would duplicate C.42: If a constructor cannot construct a valid object, throw an exception (which also has guidance for when two-stage initialization may appear desirable)

**Comment by thatbrod** [comment] 2015-10-04 22:05
These guidelines don't apply to your pre-11 code base.  In modern 
C++(11+) code, init and free functions have no place.

**Comment by grahamreeds** [comment] 2015-10-04 22:10
The problem isn't a that the constructor is creating an invalid object but
the coder isn't using the constructor to construct the object. For this
issue whether the object is constructed properly is immaterial (but can be
listed a downside to using init()).

The reasoning to me reads like a 'C++ for C programmers' example, not that
pre-11 you couldn't chain constructor which you should be doing.

GR

**Comment by grahamreeds** [comment] 2015-10-04 22:15
I agree. However I believe the example is poor. I haven't seen
init()/free() functions without a reason in a class ever and I've been
coding now for since 94.

The main reason you have init functions is due to not being able to chain
constructors and now you can which is what I believe you should be
highlighting in the example.

GR

**Comment by richelbilderbeek** [comment] 2015-10-05 07:03
```
I haven't seen init()/free() functions without a reason in a class ever
```

In the code I have observed this, it was to allow for reuse of `init` in assignment operator:

```
MyClass& MyClass::operator=(const MyClass &rhs)
{
  if (this != &rhs)
  {
  free();
  copy(rhs);
  }
}

void MyClass::copy(const MyClass &rhs)
{
  m_x = rhs.m_x
}
```

I would love to see some good examples where constructors calling each other is preferred. I just wrote down what I observed and am curious about the community its opinion on it.

**Comment by grahamreeds** [comment] 2015-10-05 07:28
I see this a lot:
```C++
foo::foo(A a) { common(a); }
foo::foo(A a, B b) { common(a, b); }
foo::foo(A, a, B b, C c) { common(a, b, c); }
void foo::common(A a) { /* construct a valid B object; */ common(a, b); }
void foo::common(A a, B b) { /* construct a valid C object; */ common(a, b, c); }
void foo::common(A a, B b, C c) { /* now we are fully constructed do stuff with each; */ }
```

**Comment by hsutter** [comment] 2015-10-05 18:25
We agree that we want to discourage init() functions. Bjarne will take a pass writing this up.

**Comment by grahamreeds** [comment] 2015-10-06 13:08
Apologies. It appears I missed the point of the topic.

There should be section on chaining constructors to remove the anti pattern
I described.

GR.

**Comment by BjarneStroustrup** [comment] 2015-10-07 17:49
There shouldn't be such a CPL entry because C doesn't have member functions or constructors. I added a note to C.42 referring to delegating constructors, in-class member initialization, and not defining an object until you can initialize it.

**Closed by BjarneStroustrup** 2015-10-07 17:49 UTC
Labels: review
