### ISSUE TITLE
Clarification of R.30: Take smart pointers as parameters only to explicitly express lifetime semantics

### ISSUE THREAD

**Issue by vingeldal** [isocpp/CppCoreGuidelines#1671] opened 2020-08-27 13:54 UTC
The stated reason for _R.30: Take smart pointers as parameters only to explicitly express lifetime semantics_ is:

"Accepting a smart pointer to a widget is wrong if the function just needs the widget itself. It should be able to accept any widget object, not just ones whose lifetimes are managed by a particular kind of smart pointer. A function that does not manipulate lifetime should take raw pointers or references instead."

This actually doesn't provide any reasoning as to why this rule should be followed, unless you count "not following this rule is wrong" as a proper rationale. I would like to be constructive and provide a concrete proposal on how to improve it but I'm not sure I fully understand the thinking behind this rule.

**Comment by MikeGitb** [comment] 2020-08-27 14:31
> This actually doesn't provide any reasoning as to why this rule should be followed

Why is

> It should be able to accept any widget object, not just ones whose lifetimes are managed by a particular kind of smart pointer.

not reasoning enough?

**Comment by shaneasd** [comment] 2020-08-27 15:32
Is R.30 just a duplicate of F.7? I don't really understand the distinction. @vingeldal, have a read of F.7 and see if it addresses your concerns. I think it does which possibly suggests that the solution is to simply have R.30 point to F.7 (or remove it entirely) rather than try to recreate it.

**Comment by cubbimew** [comment] 2020-08-31 14:16
F.7 says "See further in R.30", so presumably R.30 is meant to expand on the points made in F.7, but indeed they are near duplicate at this point.

**Comment by vingeldal** [comment] 2020-08-31 18:12
F.7 does indeed seem very similar to R.30 and F.7 does actually express the reasoning a bit more clearly IMO.
I would be in favor of what @shaneasd proposed, having R.30 point to F.7, and preferable *only* point to F.7 and not saying anything else.

**Comment by hsutter** [comment] 2020-09-03 18:25
Editors call: We agree the rules should be merged, @cubbimew to merge the rules and leave the other one as an empty forward (we do it this way to preserve any tools referring to the existing anchors).

**Closed** 2020-09-04 10:14 UTC
