### ISSUE TITLE
Allow protected copy operations in C.67

### ISSUE THREAD

**Issue by adah1972** [isocpp/CppCoreGuidelines#1777] opened 2021-04-19 11:50 UTC
I think the purpose of C.67 is very clear: we should avoid object slicing. However, `delete`ing all copy/move operations might be overly restrictive. We want to forbid the copy construction/assignment of the derived object to the base object, but often not the derived object per se. It might be that the derived object is usually created on the stack, and passed to the base class (interface) for certain operations. So a `clone` method would be overkill, and force the new object to be created on the free store.

In those cases, a simple solution can be make the copy-constructor and assignment operator `protected`. Then, both purposed are achieved:

1. You cannot copy the derived object to the base object;
2. You can still copy the derived object to another derived object.

**Comment by MikeGitb** [comment] 2021-04-19 14:33
Even worse: You usually need access to the copy constructor of the base class in order to implement a clone function in the derived type (or it at least simplifies it significantly). I remember posting this already somewhere in another issue or PR, but can't remember what came out of it.

**Comment by beinhaerter** [comment] 2021-04-28 19:56
This is a duplicate of issue #1151 which had some discussion ongoing when it was created, but unfortunately is now open since 3 years without any outcome.

**Comment by MikeGitb** [comment] 2021-04-28 22:18
Yep, that's what I had in mind.  Thanks for looking it up.

**Comment by hsutter** [comment] 2021-06-17 18:21
Editors call: Duplicate of #1151, but you're right that we owe an answer to #1151 (sorry for the lag).

**Closed by hsutter** 2021-06-17 18:21 UTC
Labels: duplicate
