### ISSUE TITLE
Specify syntax for suppression of enforcements

### ISSUE THREAD

**Issue by mgehre** [isocpp/CppCoreGuidelines#336] opened 2015-10-15 20:18 UTC
On rule [1] mentions that 
   
    [[suppress(types)]]

can be used to suppress the warnings for that rule. This should be specified in more detail:
1) What arguments to suppress are supported? type(s), bounds, lifetime? Should more detailed suppressions be available (e.g."bounds.pointer_arithmetic")?
2) Where is this attribute allowed? I guess on functions
```
[[suppress(bounds)]] void f(char* p) {
  p[3] = 1; //pointer arithmetic warning is suppressed
}
```
and code blocks
```
void g (char* p) {
  [.. do something safe ...]
  [[suppress(bounds)]] {
    p[3] = 1; //pointer arithmetic warning is suppressed
  }
  [.. do something safe ...]
}
```
Are there other cases?

I'm currently implementing checks for the type and bounds profile in clang-tidy, and would like to add this functionality when specified.

[1] https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#-type8-avoid-reading-from-varargs-or-passing-vararg-arguments-prefer-variadic-template-parameters-instead

**Comment by mgehre** [comment] 2015-10-15 20:19
Oh, this is a duplicate of #200.

**Comment by gdr-at-ms** [comment] 2015-11-01 19:46
Closing as duplicate of #200 .

**Closed by gdr-at-ms** 2015-11-01 19:46 UTC
