### ISSUE TITLE
How about a Discord server so we can chat about the guidelines a little less asynchronously?

### ISSUE THREAD

**Issue by jeffreylindsey** [isocpp/CppCoreGuidelines#1244] opened 2018-08-02 17:06 UTC
The idea is to have a place on the internet where all the active editors, contributors, and users of the C++ Core Guidelines can chat about these guidelines in (close to) real-time.  This GitHub repository provides sufficient means for asynchronous communication, but a chat server would better facilitate quick questions and discussions.

If a place for this already exists, then it would be helpful to have a link to that place in a location that is easy to find.  Perhaps in the README or CONTRIBUTING documents.  If such a place *does not* currently exist, then a new Discord server, created or overseen by an editor, would be ideal.

Note: Slack is not recommended for this purpose because of how older data becomes unavailable for users who are not on a paid plan.  Discord is recommended instead, because of its similar functionality without having the same issue.  Discord also has the advantage of improved support for roles, which may be a benefit to editors and contributors.

**Comment by neilmacintosh** [comment] 2018-08-02 17:11
@jeffreylindsey I don't know about the other editors (but I suspect they're in a similar position), but I simply don't have the availability to chat about the guidelines in real-time (or anything close to it). We all have "day jobs" ;-)

**Comment by KateGregory** [comment] 2018-08-02 17:16
I know, having 17 apps open for talking to people is super annoying. But a chat server could serve as a place to recruit helpers, or discuss things quickly when you happen to have 5 minutes waiting for a conference call to start or a bus to arrive. It could be a way to build a community around the guidelines and increase adoption.

**Comment by hsutter** [comment] 2018-08-02 17:40
I appreciate the interest, but my gut feel is what Neil said… the Issues process is working well and already consumes our available bandwidth.

A major benefit of Issues comment threads is that they are reusable: They can be efficiently referred to again to avoid duplication. A major drawback of chat is that effort there is often… how can I put this kindly… "inefficient" and wasted on one-off silo'd conversations that aren’t easily referenceable and reusable.

@KateGregory Good point, but isn't "respond when you have 5 minutes" an example of asynchronous communication, not synchronous communication which is what was asked for? (And I think here the asynchrony is a feature, not a bug.) If I have 5 minutes, I can already respond to comment threads here -- as I'm doing now. :) I personally wouldn't have time for synchronous chat, and I no longer even try to use Facebook, Twitter, Slack, Discord, etc.... no time. (One exception: I usually engage lightly on Twitter during CppCon week only.)

**Comment by jeffreylindsey** [comment] 2018-08-02 17:58
Great feedback so far!  The intent here is not to require anybody to dedicate their time to this chat, but to provide an official place for those who do wish to participate.  Part of the reason for this issue is to express that there is a desire for such a place.  For anybody who does not have the time or energy to participate, that's totally understandable.

**Comment by hsutter** [comment] 2018-08-06 15:10
Thanks for the suggestion. Three of the editors have responded on this thread that they couldn't participate, and I know two of the others could it. So the Discord server would not be used by the editors. SoI'm going to close this for now, but mark it 'deferred' as something we could look again in the future if things change.

However, there's nothing wrong with anyone setting up their own separate Guidelines discussion chat area anywhere they like. If there's a group that wants to chat about the Guidelines and possibly generate some Issues and PRs as a result of that discussion, that would be helpful and appreciated.

**Closed by hsutter** 2018-08-06 15:10 UTC
Labels: deferred
